version: 2.1

executors:
  node:
    docker:
      - image: cimg/node:17.2.0

commands:
  curl:
    parameters:
      url:
        type: string
        default: "https://circleci.com/"
    steps:
      - run: curl << parameters.url >>

  echo:
    parameters:
      message:
        type: string
        default: "hello world"
    steps:
      - run: echo << parameters.message >>

jobs:
  hello-job:
    executor: node  # usa el ejecutor node definido arriba
    steps:
      - checkout    # revisa el código en el directorio del proyecto
      - echo:       # ejecuta el comando echo
          message: "Hello from CircleCI!"

workflows:
  my-workflow:
    jobs:
      - hello-job
